### ISSUE TITLE
Transformer outputs incorrect paths when in subdirectory

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/polymer-dart#34]
If you are building the contents of web and an entry point is in a sub directory of web then the transformer will fail to output the right path when executing pub build.

Example transformer.

```yaml
transformers:
- polymer:
    entry_points:
    - web/index.html     # Builds fine
    - web/sub/index.html # Builds incorrectly
```

The following is the behavior of the transformer in the sub folder.

`pub build`
* packages/web_components/webcomponents.min.js :-1: 
* packages/web_components/dart_support.js :-1: 
* ../packages/polymer/src/js/polymer/polymer.min.js :+1: 

`pub build --mode=debug`
* packages/web_components/webcomponents.js :-1: 
* packages/web_components/dart_support.js :-1: 
* ../packages/polymer/src/js/polymer/polymer.min.js :+1: 
* packages/browser/dart.js :-1:
