### ISSUE TITLE
Pub: Get Dependencies does not work for version 1.0.0-rc.1

### ISSUE THREAD

**Issue by supermuka** [dart-lang/polymer-dart#612]
Hi,

I am following the documentation for set the dependecies on pubspec.yaml: 
https://github.com/dart-lang/polymer-dart/tree/1.0.0-rc.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  polymer: '1.0.0-rc.1'

transformers:
- polymer:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart

I am using the WebStorm 11 EAP.

Occur this error:

Working dir: D:\Users\Administrador\WebstormProjects\testPolymer
C:\dart-sdk\bin\pub.bat get
Resolving dependencies...
Package polymer has no versions that match 1.0.0-rc.1 derived from:
- testPolymer depends on version 1.0.0-rc.1
Process finished with exit code 1

Am I doing  something wrong?

**Comment by zoechi** [comment]
This might help http://stackoverflow.com/questions/32242736/import-and-make-use-of-polymer-dart-0-17-dev-preview

**Comment by jakemac53** [comment]
The official release candidate has not yet been released, so you need to use a git dependency in the meantime:

```yaml
dependencies:
browser: '>=0.10.0 <0.11.0'
polymer:
  git:
    url: git@github.com:dart-lang/polymer-dart.git
    ref: 1.0.0-rc.1
```
