### ISSUE TITLE
"Missing entry point: tool/status.dart" but it's there

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#636]
`pub serve` prints

> [Info from Reflectable on polymer_elements_demos|ReflectableTransformed]:
Missing entry point: tool/status.dart

When I load a page from the `polymer_elements_demos` project (for example `web/index.html`

```yaml
- reflectable:
    entry_points:
    - web/index.dart
    - tool/status.dart
```
Maybe related to the directory `tool` instead of `web`

This seems not to cause any harm, all seems working fine, still wondering if this needs some fix.
