### ISSUE TITLE
I get "A transformer imported unknown package "html5lib" (in "package:html5lib/dom.dart")."

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#69]
When I run pub upgrade

```yaml
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  core_elements: ">=0.2.0 <0.8.0"
  polymer: '>=0.12.0+5 <0.17.0'

dev_dependencies:
#  grinder: '>=0.7.0 <0.8.0'
  paper_elements: ">=0.1.0+2 <0.8.0"
#  test: '>=0.12.0 <0.13.0'

transformers:
- polymer:
    entry_points:
    - example/example01.html
    - example/example02.html
    - example/example03.html
```
