### ISSUE TITLE
paper-menu, select method adds extra value to selectedValues

### ISSUE THREAD

**Issue by jonboj** [dart-lang/polymer-dart#691]
##### Environment/Code
A paper-menu with multi selection.
Dartium
html
```
<paper-button on-tap="deSelectAll">Deselect All</paper-button>
<paper-menu id="id_pm" multi selected-values="{{selectedValues}}">
      <paper-item>A0</paper-item>
      <paper-item>A1</paper-item>
</paper-menu>

```
dart
```
...
@property
List<String> selectedValues = [];
...
PaperMenu pm = $$('#id_pm') as PaperMenu;
pm.select('0');
...
```
##### What is expected
For a value in `selectedValues` should `select` insert and remove the value from `selectedValues`.

##### Actual outcome
First time `select(v)` is called an extra instance of `v` is added into the `selectedValues`. This instance remains when the item is deselected with tap from Dartium.

##### Howto reproduce
* Select an item in a `paper-menu`, with tap from the Dartium browser. 
* From dart use the method `select` to deselect the item selected above. E.g. if first then `select('0')`.
 This will leave two instances of 0 in `selectedValues`.
* In Dartium tap on the item this will only remove one instance of 0 in `selectedValues`.
* In Dartium tap on the item, this will leave two instances of 0 in `selectedValues`.

console print dumps.
```
SelectTest.onIronSelect, selected : [0]
SelectTest.onIronSelect, selected : []
SelectTest.onIronSelect, selected : [0]
SelectTest.deSelectAll
SelectTest.deSelectAll, [0]
SelectTest.deSelectAll, select('0')
SelectTest.onIronSelect, selected : [0, 0]
SelectTest.onIronSelect, selected : [0]
SelectTest.onIronSelect, selected : [0, 0]
```
Cut from pub.yaml
```
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  polymer_elements: 1.0.0-rc.8
  browser: ^0.10.0
  reflectable: ^0.5.0
  polymer_interop: ^1.0.0-rc.5
```

**Comment by zoechi** [comment]
Sounds similar to polymer_elements#92 
Might be an issue with array-selector. I guess this is used for selection of such lists (not sure).

**Comment by jonboj** [comment]
Interesting, this gave me an clue. Debugging into iron-multi-selectable.html

The tap selection from Dartium puts an int 0 into this.selectedValues, but the select method from Dart comes with and String "0" so at this line
https://github.com/PolymerElements/iron-selector/blob/master/iron-multi-selectable.html#L125
 it don't matches and pushes "0" into the array, this gives the two instance. Same index but different int/String reprensentation.

**Comment by jonboj** [comment]
Reproduced with  `polymer_elements: ^1.0.0-rc.9`

From pubspec.yaml

```
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.17
  web_components: '>=0.11.3 <0.13.0'
```
