### ISSUE TITLE
Polymer 1.0.0-rc.18 is not compatible with Angular2 2.0.0-beta.22 and higher

### ISSUE THREAD

**Issue by dentra** [dart-lang/polymer-dart#716]
### Description
Due to Angular2 2.0.0-beta.22 changes and issue https://github.com/dart-lang/angular2/issues/98
Polymer 1.0.0-rc.18 is longer compatible with it and higher

#### Steps to Reproduce
1. create pubspec.yaml
2. add dependecy: angular2: 2.0.0-beta.22
3. add dependecy: polymer: ^1.0.0-rc.18 depndency 
4. dependecy: analyzer: '>=0.28.0 <0.29.0'
5. run: pub get

#### Expected Results
all dependicies updated and precompiled

#### Actual Results
pub get show error:

> Resolving dependencies... (10.4s) 
> Package polymer has no versions that match >=1.0.0-rc.18 <2.0.0 derived from:
> \- test depends on version ^1.0.0-rc.18```

**Comment by zoechi** [comment]
You might be able to use `dependency_overrides` to work around until an updated version is available.

**Comment by dentra** [comment]
@zoechi thanks, but `dependency_overrides` does not help because of:
```
Error on line 25, column 5 of ../../../.pub-cache/hosted/pub.dartlang.org/initialize-0.6.2+2/pubspec.yaml: Error loading transformer: No constructor 'SdkAnalysisContext' with matching arguments declared in class 'SdkAnalysisContext'.

NoSuchMethodError: incorrect number of arguments passed to method named 'SdkAnalysisContext'
Receiver: Type: class 'SdkAnalysisContext'
Tried calling: SdkAnalysisContext(...)
Found: SdkAnalysisContext(AnalysisOptions)
    $include: '**/*_test.*'
    ^^^^^^^^^^^^^^^^^^^^^^^^
Error on line 23, column 5 of ../../../.pub-cache/hosted/pub.dartlang.org/polymer_interop-1.0.0-rc.10/pubspec.yaml: Error loading transformer: No constructor 'SdkAnalysisContext' with matching arguments declared in class 'SdkAnalysisContext'.

NoSuchMethodError: incorrect number of arguments passed to method named 'SdkAnalysisContext'
Receiver: Type: class 'SdkAnalysisContext'
Tried calling: SdkAnalysisContext(...)
Found: SdkAnalysisContext(AnalysisOptions)
    $include: test/**_test{.*,}.html
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error on line 27, column 5 of ../../../.pub-cache/hosted/pub.dartlang.org/web_components-0.12.3/pubspec.yaml: Error loading transformer: No constructor 'SdkAnalysisContext' with matching arguments declared in class 'SdkAnalysisContext'.

NoSuchMethodError: incorrect number of arguments passed to method named 'SdkAnalysisContext'
Receiver: Type: class 'SdkAnalysisContext'
Tried calling: SdkAnalysisContext(...)
Found: SdkAnalysisContext(AnalysisOptions)
    $include: '**/*_test.html'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Maby it is possible to do something to pass this errors?

**Comment by southpawflo** [comment]
@dentra I am getting the same thing as you. trying to start playing with polymer using an empty project, new to dart and web programming altogether. kind of a showstopper at the moment

**Comment by dam0vm3nt** [comment]
hello,  I expect soon some big news about polymer and dart that will fix most of these problems.

In the meanwhile you can try using the following - yet to be released - repositories in your ovverrides for dart and polymer (or check-out the PR's that are still not merged if you prefer)  :: 
```
polymer:
    hosted:
      name: polymer
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.19.unofficial.1"
polymer_interop:
    hosted:
      name: polymer_interop
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.10.exp.20161031.2"
polymer_elements:
    hosted:
      name: polymer_elements
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.11+4"
```

You will get support for `polymer-1.7.1` as long as latest versions of `polymer_elements`.

**EDIT** : you can also put those dependencies as normal dependencies and do a `pub upgrade`. You should be able to upgrade to a more recent version of analyzer then.
